global using ToDo2022.Database;
global using Microsoft.AspNetCore.Mvc;
global using ToDo2022.Database.Domain;
global using Microsoft.EntityFrameworkCore;
global using ToDo2022.Database.Dto;
global using pi8.ez.ApiServices;
global using pi8.ez.ApiServices.Models;
global using pi8.ez.ApiServices.Interfaces;
global using pi8.ez.ApiServices.Extensions;
